spring:
  application:
    name: spot
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: spot-backend


encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-ms: ${JWT_ACCESS_TOKEN_EXPIRE_MS}
  refresh-token-expire-ms: ${JWT_REFRESH_TOKEN_EXPIRE_MS}

app:
  default:
    profile-image: ${DEFAULT_PROFILE_IMAGE_PATH}