spring:
  application:
    name: spot
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:1MB}       # 파일 1개당 최대 크기
      max-request-size: ${MAX_REQUEST_SIZE:10MB}    # 요청 1번당 최대 크기 (여러 파일 동시 업로드 시)

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: spot-backend


encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-ms: ${JWT_ACCESS_TOKEN_EXPIRE_MS}
  refresh-token-expire-ms: ${JWT_REFRESH_TOKEN_EXPIRE_MS}


file:
  upload-dir: ${UPLOAD_DIR}
app:
  default:
    profile-image: ${DEFAULT_PROFILE_IMAGE_PATH}